name = "KROME"
uuid = "5c8b4ca1-0b6a-42b8-94b6-413025dcddf5"
authors = ["Michael Schlottke-Lakemper <mschlott@math.uni-koeln.de>"]
version = "0.1.0"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
CBinding = "0.9"
Reexport = "1.0"
