name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'
      - 'docs/**'
  workflow_dispatch:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: ${{ matrix.os }} - Julia ${{ matrix.version }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.5'
          # - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - name: Set up gfortran-10 as gfortran and gcc-10 as gcc (macOS only)
        if: contains(matrix.os, 'macOS')
        run: |
          mkdir -p "$HOME/mypath"
          echo "$HOME/mypath" >> $GITHUB_PATH
          printf '#!/bin/bash'"\ngfortran-10 \"\${@}\"\n" > "$HOME/mypath/gfortran"
          chmod a+x "$HOME/mypath/gfortran"
          printf '#!/bin/bash'"\ngcc-10 \"\${@}\"\n" > "$HOME/mypath/gcc"
          chmod a+x "$HOME/mypath/gcc"
      - name: Test gfortran and gcc (macOS only)
        if: contains(matrix.os, 'macOS')
        run: |
          gfortran --version
          gcc --version
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ""
      - uses: julia-actions/julia-runtest@v1
        env:
          PYTHON: ""
      - uses: julia-actions/julia-processcoverage@v1
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.version }}-${{ matrix.os }}-${{ matrix.arch }}
          parallel: true
          path-to-lcov: ./lcov.info

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
